#!/bin/bash

cd "`dirname "$0"`"

# Kill existing processes
lsof -t -i tcp:8080 | xargs kill

# Sass publish

map_file="bin/css/main.css.map"
[ -e $map_file ] && rm $map_file
sass --style compressed --no-source-map scss:bin/css

# Webpack publish 

npm run build

# Remove license generated by webpack manually
license_file="bin/js/app.js.LICENSE.txt"
[ -e $license_file ] && rm $license_file

echo ""
echo "DONE"

# rm -r "docs"
# cp -r "bin" "docs"

$SHELL
